user:
  path: /users
  controller: AppBundle:User:index
  methods: [GET]
user.show:
  path: /users/{id}
  defaults: {_controller: AppBundle:User:show}
  methods: [GET]
  requirements:
          id: '\d+'
user.store:
  path: /users
  defaults: {_controller: AppBundle:User:store}
  methods: [POST]
user.update:
  path: /users/{id}
  defaults: {_controller: AppBundle:User:update}
  methods: [PUT]
  requirements:
          id: '\d+'
user.destroy:
  path: /users/{id}
  defaults: {_controller: AppBundle:User:destroy}
  methods: [DELETE]
  requirements:
          id: '\d+'
