AppBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: false
      column: name
    username:
      type: string
      length: 255
      nullable: false
      column: username
    password:
      type: string
      length: 255
      nullable: false
      column: password
